# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-27 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coding_test', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vdobject',
            name='id',
        ),
        migrations.AddField(
            model_name='vdobject',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vdobject',
            name='value',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vdobject',
            name='key',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
