# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-27 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding_test', '0002_auto_20161127_0721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vdobject',
            name='created',
        ),
        migrations.AddField(
            model_name='vdobject',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vdobject',
            name='value',
            field=models.TextField(blank=True),
        ),
    ]
